server:
  port: 8080

spring:
  application:
    name: ami-invisible
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ami_invisible}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Africa/Douala

app:
  jwt:
    secret: ${JWT_SECRET:changez-cette-cle-secrete-en-production-au-moins-256-bits-svp-franck}
    expiration-admin-ms: ${JWT_EXP_ADMIN:86400000}       # 24h
    expiration-participant-ms: ${JWT_EXP_PARTICIPANT:15552000000} # 180 jours (~6 mois)
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:5175}

logging:
  level:
    com.franck.amiinvisible: INFO
